# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a094638552b7f892785425dd8968dfc13b47794c62a43341dbffa83ef6484d1535dff86749040b72698411f49b2d4a7ec65adc979f5186c1bc5ceb1fa1823d70

test:
  secret_key_base: b47ef2386b175583a40c928ea0637aa59f18a9cd228a85b896204f3835407cbca93abfcd9aee040e13aef4e673846ee16ca533f3293ffa85f55b5d641944607c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
